modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="Custom"

issueTrackerURL="https://github.com/milkev/More-Baked-Foods/issues" #optional

[[mods]] #mandatory
itemIcon="morebakedfoods:fried_egg"

modId="morebakedfoods" #mandatory

logoFile="icon.png"

version="1.1.1" #mandatory

displayName="MoreBakedFoods" #mandatory

credits="Thanks for this mod goes to Milkev and sp4destech for making the Fabric version of this mod" #optional

authors="RedRoseWarrior1 aka DevMaster1015 for the forge version and Milkev and sp4destech for the fabric version" #optional

description='''
adds some baked foods'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.morebakedfoods]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[36,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.morebakedfoods]]
    modId="minecraft"
    mandatory=true
versionRange="[1.16.5,1.17]"
    ordering="NONE"
    side="BOTH"